#!/bin/sh
#  preinstall.sh

echo "Presets\scripts\TAMSScripts\preinstall"
echo "PID: $$; PPID: $PPID; Args: $(ps -o args= $$)"

# make sure that start of main installer pkg is signalled to background script
# normally this signal file is already deleted by tiny pkg at this point
rm -f "/tmp/.sig_CyanSoft_ManPkgMS_downloadPending"

######################### sendStat begin
urlencode()
{
	local length="${#1}"
	for (( i = 0; i < length; i++ ))
	do
		local c="${1:i:1}"
		case $c in
			[a-zA-Z0-9.~_-]) printf "$c" ;;
			*) printf '%%%02X' "'$c"
		esac
	done
}

os_ver=$(sw_vers -productVersion)

serialExact="$(ioreg -c IOPlatformExpertDevice -d 2 | grep IOPlatformSerialNumber | sed -e 's/.*\"\(.*\)\"/\1/')"

serial=$(echo $serialExact | openssl base64 -e)
garbage="qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm"
result=""


for (( i=0; i<${#serial}; i++ ))
do
	sumbol=${serial:$i:1}
	result+=$sumbol
	result+=${garbage:$i:1}
done

serial=$result

guidFile="/Library/Preferences/.2935B9C3-6E77-4C62-A7E6-01A7326DCBEB"
guid=""
if [ -f "$guidFile" ]
then
	read -r guid < "$guidFile"
fi
t=$(date +"%d/%m/%Y%k:%M:%S")
t=$(urlencode "$t")


sendStat()
{
	local phaseName=$1
	local url="http://ev.macshiny.com/version.aspx?statsType=InstallEvent&product=MacShiny&step=OnInstall&subject=$serial&caller=InstallerFull&OSVersion=$os_ver&localtime=$t&guid=$guid&Phase=$phaseName"
	echo $url
	curl -L $url
}

######################### sendStat end

USER=`ls -la /dev/console | cut -d " " -f 4`

sendStat "TrayAgentMS"

echo "unload USER:$USER Tray"
sudo -u "$USER" launchctl unload -w "/Library/LaunchAgents/com.cyan.TrayAgentMS.plist"

#killall TrayAgent - for old version
killall TrayAgent
killall TrayAgentMono

rm -rf "/Library/Application Support/CyanSoft/MacShiny/TrayAgentMS.app"
rm -rf "/Library/LaunchAgents/com.cyan.TrayAgentMS.plist"

sendStat "DeletedTrayAgentMS"

exit 0